// Generated by Lasy AI - https://lasy.ai
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";
// Import all available fonts for AI usage
import "../lib/fonts";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "ShapeMe - Acompanhamento Corporal",
  description: "Acompanhe sua evolução de peso e medidas corporais",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <head>
        <Script src="/lasy-bridge.js" strategy="beforeInteractive" />
        {/* Suprimir erros do MetaMask e outras extensões */}
        <Script id="suppress-extension-errors" strategy="beforeInteractive">
          {`
            // Suprimir erros de extensões do navegador (MetaMask, etc)
            window.addEventListener('error', function(e) {
              if (e.filename && e.filename.includes('chrome-extension://')) {
                e.preventDefault();
                e.stopPropagation();
                return false;
              }
            });
            
            window.addEventListener('unhandledrejection', function(e) {
              if (e.reason && e.reason.stack && e.reason.stack.includes('chrome-extension://')) {
                e.preventDefault();
                e.stopPropagation();
                return false;
              }
            });
          `}
        </Script>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
